source 'https://api.berkshelf.com'
## TODO should really pick tags, not master, to avoid nasty upgrade suprises..
cookbook 'apt',             github: 'opscode-cookbooks/apt',        tag: 'master'
cookbook 'fail2ban',        github: 'opscode-cookbooks/fail2ban',   tag: 'master'
cookbook 'ntp',             github: 'opscode-cookbooks/ntp',        tag: 'master'
cookbook 'python',          github: 'opscode-cookbooks/python',     tag: 'master'
cookbook 'ssh_known_hosts', github: 'opscode-cookbooks/ssh_known_hosts', tag: 'master'
cookbook 'haproxy',         github: 'opscode-cookbooks/haproxy',    tag: 'master'

cookbook 'redisio',         github: 'brianbianco/redisio', tag: 'master'

cookbook 'afw',             github: 'irccloud/afw',                 tag: 'master'
cookbook 'timezone-ii',     github: 'irccloud/timezone-ii',         tag: 'master'
cookbook 'sysctl',          github: 'irccloud/sysctl-cookbook',     tag: 'master'

cookbook 'basebox', path: './basebox'
cookbook 'clientroomradio', path: './clientroomradio'
