name             "clientroomradio"
maintainer       "YOUR_NAME"
maintainer_email "YOUR_EMAIL"
license          "All rights reserved"
description      "Installs/Configures basebox"
long_description "blah"
version "1.0.0"
depends          "basebox"
depends          "redisio"
depends          "haproxy"
